name: Flutter Android CI

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Flutter Version
        run: flutter --version

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK Split Per ABI
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: |
            build/app/outputs/flutter-apk/*.apk

